# Site

title: Introduction to Python for GIS
handouts:
 - worksheet.ipynb
 - data/
 - data/README.md
tag: v0.0
lesson: 6
instructor: Ian Carroll
authors:
 - Ian Carroll

# Slides

slide_sorter:
 - intro
 - structs
 - comps
 - packages
 - numpy
 - gp
# - qgis
# - pg
# - conclude
 
#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-style/v1.3/docs
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.5.0

# Jekyll

markdown: kramdown
collections:
  - slides
